### PR TITLE
fix typo in command to install dependencies

### PR DESCRIPTION
**Pull request by StoneyJackson**

### CODE REVIEW

**Comment by hawzie197** [comment]
Completely missed that one. Good catch!

**Comment by StoneyJackson** [comment]
Did you mean to merge this?

**Comment by StoneyJackson** [comment]
I'm going to tac on to this another fix for travis CI

**Comment by StoneyJackson** [comment]
Nevermind... I see that 2b6afe62c94cc19a1cd7e21791990fe6e550e1f0 has the changes.

**Pull request closed without merging**
