### PR TITLE
split .gitignore into separate files

### PR DESCRIPTION
**Pull request by StoneyJackson**
Reasons

1. Keep our .gitignore rules organized.

2. Easily drop in templates from https://github.com/github/gitignore .

3. Reduce the risk of folks inadvertantly deleting the carriage returns at the
   end of Icon in macOS.ignore, because now this would only happen when editing
   macOS.gitignore.

Changes

1. Create a new .gitignore.d/ directory.

2. Place each section of .gitignore into a separate file in .gitignore.d/
   organized in the same structure used by https://github.com/github/gitignore

3. Add a message to the to of the .gitignore to warn folks not to edit it
   directly and to give directions on how to make a change and regenerate
   .gitignore.

Our .gitignore is large. It has many sections related to different
tools used by this project. To make it easier to find the relevant
rules, and to make it more clear

### CODE REVIEW

**Review by alhansrisuk — COMMENTED** [review]
Looks good 👍

**Review by hawzie197 — APPROVED** [review]
Good stuff 💯

**Comment by StoneyJackson** [comment]
@alhansrisuk @hawzie197 Thanks for the positive feedback! Before I can merge, I need an official review. I think there is a magic button to start the review.

**Comment by StoneyJackson** [comment]
I think @hawzie197 made an official review. @alhansrisuk can you make your review official?

**Review by alhansrisuk — APPROVED** [review]

**Pull request merged**
