### PR TITLE
Research and setup Vagrant + Docker

### PR DESCRIPTION
**Pull request by adhikaribiraj**

### CODE REVIEW

**Comment by StoneyJackson** [comment]
I tried to review this, but I don't know how to use it. Will instructions in README.md be updated to explain how to install/deploy using vagrant?

FYI, I'm able to install using the current README.md. Maybe we should go with the current install instructions for now?

**Comment by adhikaribiraj** [comment]
> I tried to review this, but I don't know how to use it. Will instructions in README.md be updated to explain how to install/deploy using vagrant?
> 
> FYI, I'm able to install using the current README.md. Maybe we should go with the current install instructions for now?

There still some issues with this PR that I am working on fixing. However, I do agree that we should go with current install instructions if I cannot get it working by tomorrow. Once it works, it will make installing requirements easy and provide consistent dev environments. Read.me will be updated.

**Comment by StoneyJackson** [comment]
Good to know. In case it helps. I tried running `vagrant up` and here is what I got

```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'bento/ubuntu-16.04' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: 2.3.5
==> default: Loading metadata for box 'bento/ubuntu-16.04'
    default: URL: https://vagrantcloud.com/bento/ubuntu-16.04
==> default: Adding box 'bento/ubuntu-16.04' (v2.3.5) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/bento/boxes/ubuntu-16.04/versions/2.3.5/providers/virtualbox.box
==> default: Successfully added box 'bento/ubuntu-16.04' (v2.3.5) for 'virtualbox'!
==> default: Importing base box 'bento/ubuntu-16.04'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'bento/ubuntu-16.04' is up to date...
==> default: Setting the name of the VM: BEAR-Necessities-Market_default_1550449950902_95186
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 80 (guest) => 5000 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "22f2fc8c-c564-4466-b887-b05330df6878", "--type", "headless"]

Stderr: VBoxManage: error: The virtual machine 'BEAR-Necessities-Market_default_1550449950902_95186' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
```

**Comment by adhikaribiraj** [comment]
For anyone who wants to play with this:

First you need to install vagrant on your computer.

**Comment by hawzie197** [comment]
Not sure why this failed. It said that travis does not have python 3.5. Will try to re-run

**Comment by adhikaribiraj** [comment]
The following are instructions on how to setup to work with this branch. At this time please DO NOT PUSH anything to this branch without discussing first. 

For terminal, I recommend downloading Git Bash

On your computer do the following:
1. Install Virtualbox
https://www.virtualbox.org

2. Install Vagrant
https://www.vagrantup.com/downloads.html

NOTE: **No** additional Vagrant tools such as VBoxManage are required

3. Go into the project directory and do a `git pull` from master branch

4. `git checkout set-up-vagrant`

5. `vagrant up`
This will boot up a virtual machine with docker containers that run the Flask and React app.

6. To go into the virtual machine do `vagrant ssh` then `cd /vagrant`
Now you are in the project directory inside the VM.

7. From here you can run commands on the flask app such as migrations
Example: `sudo docker-compose exec web-dev flask db upgrade`

8. You can also bring down or up the docker containers:
`sudo docker-compose up -d` 
The `-d` option will run it in detached mode without printing logs

OR

`sudo docker-compose down`

**Comment by StoneyJackson** [comment]
Status?

How important is this?

**Pull request closed without merging**
