### PR TITLE
Setup vagrant docker

### PR DESCRIPTION
**Pull request by adhikaribiraj**

### CODE REVIEW

**Comment by KevinTran000** [comment]
CI failure is expected due to moving `requirements.txt` to `backend` folder.

EDIT: There is several issues that still need to be resolved, so not ready for review yet.
EDIT2: This would resolve issue #94

**Comment by StoneyJackson** [comment]
I just added a bunch of reviewers. I don't think this is ready for review yet. But it doesn't hurt to keep our eyes on it.

**Comment by KevinTran000** [comment]
Why was this PR renamed? I think it would be more confusing/unhelpful in the future if I was trying to find this PR again or when other people reference this PR.

EDIT: Also, why is the branch deleted? That would cause double work / re-inventing progress that was done. Someone else in the future could pick up what was unfinished if the branch is still there sitting inactive.

**Comment by KevinTran000** [comment]
For future reference, this PR was closed and new PR (#103) was created to split this large work into a smaller more manageable chunk.

Again the issue that corresponds to this PR and the new PR is issue #94.

**Comment by StoneyJackson** [comment]
I agree with @KevinTran000 . Use labels to indicate that this is abandoned, or simply make a comment, and then close it. Likewise with the PR.

**Comment by StoneyJackson** [comment]
Got the branch back

**Comment by StoneyJackson** [comment]
Title restored

**Pull request closed without merging**
