### PR TITLE
Lock python packages to current working versions #86

### PR DESCRIPTION
**Pull request by alhansrisuk**

### CODE REVIEW

**Review by hawzie197 — CHANGES_REQUESTED** [review]
Please update this to reflect security vulnerability found in sqlalchemy

**Comment by hawzie197** [comment]
Here is a reference: https://github.com/LibreFoodPantry/BEAR-Necessities-Market/network/alerts

update this requirement in requirements.txt to mitigate this risk.
`SQLAlchemy>=1.3.0`

**Comment by StoneyJackson** [comment]
I don't think we should include `SQLAlchemy>=1.3.0` in `requirements.txt`

First, if we must constrain a version of a dependency we should do so in `requirements-to-freeze.txt` and not in `requirements.txt`.

Second, `SQLAlchemy` is an indirect dependency. We depend directly on `Flask-Migrate` which depends on `Flask-SQLAlchemy` which depends on `SQLAlchemy`. We need to allow those projects to determine which version of `SQLAlchemy` to use. If this causes a vulnerability, then we have to decide whether to continue to use `Flask-Migrate`. But the good news is that this dependency chain has allowed us to upgrade to the most recent version of `SQLAlchemy` (which is 1.3.3), as is demonstrated in `requirements.txt`. This tells me that the projects that are responsible for keeping up with such updates, are.

**Comment by StoneyJackson** [comment]
FYI, the `requirements.txt` works for Python 3.5 and 3.6, but not 3.7.

**Review by StoneyJackson — APPROVED** [review]

**Comment by StoneyJackson** [comment]
@hawzie197 I value your opinion, and I don't want to merge until you are satisfied. If I can't convince you, then there may be something wrong with my thinking. So please let me know either way.

**Comment by StoneyJackson** [comment]
Merging with verbal approval from @hawzie197 .

**Pull request merged**
