### PR TITLE
setup heroku pipeline

### LINKED ISSUE #60: Deploy application to heroku dev server
Deploy the app to a test server allowing us to showcase the application to our client. Also to test out application security, cost, and scalability.

A user who initially deploys the application should deploy to their heroku branch, and then can transfer ownership of the application to Stony/Organization owner later on.

Reference: https://www.heroku.com/

Use MySQL as database.
Not about the deployment button. This is for development.
Continuous deployment.

### PR DESCRIPTION
**Pull request by hawzie197**
Fixes #60

### CODE REVIEW

**Comment by KevinTran000** [comment]
@hawzie197, can you please post an update on where the status is on this PR, for documentation? (Is it just waiting for reviews, still have X stuff left to implement [if so what is left to do], or actually blocked?)

**Comment by KevinTran000** [comment]
For future reference, this PR would resolve issue #60.

**Comment by StoneyJackson** [comment]
@KevinTran000 Thanks for the grooming. Let's mark it like this: Fixes #60 . Now hopefully GitHub will know to close #60 if and when this is merged.

**Comment by StoneyJackson** [comment]
That didn't work. [Looks like](https://help.github.com/en/articles/closing-issues-using-keywords) the "Fixes #60" syntax has to go into a commit message or the PR's description. Let me see if I can edit that.

**Pull request closed without merging**
